CMakeLists.txt
examples/OpenCV/TagGenerator.hpp
src/Autonomy_Globals.cpp
src/Autonomy_Globals.h
src/Autonomy_IdentitySoftware.cpp
src/Autonomy_IdentitySoftware.h
src/interfaces/DriveBoard.cpp
src/interfaces/DriveBoard.h
src/interfaces/MultimediaBoard.cpp
src/interfaces/MultimediaBoard.h
src/interfaces/NavigationBoard.cpp
src/interfaces/NavigationBoard.h
src/main.cpp
src/util/NumberOperations.hpp

- Set C++ Version
- Update Docs to use correct email and name for @Byrdman32

General Updates

---

.devcontainer/Dockerfile_JetPack
.devcontainer/Dockerfile_Ubuntu
.devcontainer/devcontainer.json
.github/workflows/codeql.yml
.github/workflows/deploy_autonomy.yml

Upgrade OpenCV

---

.gitignore
.idea/cmake.xml
.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
.idea/runConfigurations/Autonomy_Software.xml

Removing after realizing that there isn't a vscode config included

Remove CLion Configs

---

CMakeLists.txt
tests/Example.cc
tests/Integration/README.md
tests/Unit/README.md

Add Google Test Framework

---

examples/README.md
examples/threading/ArucoGenerateTags.hpp
examples/threading/PrimeNumbers.hpp
src/main.cpp
src/util/ExampleChecker.h

1) Use the C++ preprocessor to detect if an example file has been included. 
2) Depending on that condition the RunExample function will be called and main code will be skipped.
3) If no example is included, then program will run as normal.
Only one example file at a time for simplicity.
Closes issue #59

Elegant Example Running

---

.devcontainer/devcontainer.json
.github/workflows/codeql.yml
.github/workflows/deploy_autonomy.yml
.github/workflows/docker_jetpack.yml
.github/workflows/docker_ubuntu.yml
.github/workflows/tests.yml
.github/workflows/valgrind.yml
README.md

The incorrect names of the docker images were missed in the previous Pull Request.

Fixing names of docker images

---

.github/CODEOWNERS

Set Up Codeowners

---

.devcontainer/Dockerfile_Focal
.devcontainer/Dockerfile_Jammy
.devcontainer/Dockerfile_JetPack
CMakeLists.txt
Doxyfile
src/IdentitySoftware.h

At the end of each sprint, we will iterate the minor version of Autonomy. Moving from **24.0.0** to **24.1.0**.

*** Iterate Versions ***

---

.github/workflows/deploy_autonomy.yml

- Old Format: Autonomy Software vXX.XX.XX
- New Format: vXX.XX.XX

Shorten Release Names

---

CMakeLists.txt
data/Custom_Dictionaries/Autonomy-Dictionary.txt
examples/vision/cameras/OpenBasicCam.hpp
examples/vision/tagdetection/ArucoDetectionBasicCam.hpp
examples/vision/tagdetection/ArucoDetectionZED.hpp
src/AutonomyConstants.h
src/AutonomyGlobals.cpp
src/AutonomyLogging.cpp
src/AutonomyLogging.h
src/handlers/CameraHandler.cpp
src/handlers/CameraHandler.h
src/handlers/RecordingHandler.cpp
src/handlers/RecordingHandler.h
src/handlers/TagDetectionHandler.cpp
src/handlers/TagDetectionHandler.h
src/interfaces/AutonomyThread.hpp
src/interfaces/Camera.hpp
src/main.cpp
src/vision/aruco/ArucoDetection.hpp
src/vision/aruco/TagDetector.cpp
src/vision/aruco/TagDetector.h
src/vision/aruco/TensorflowDetection.hpp
src/vision/cameras/BasicCam.cpp
src/vision/cameras/BasicCam.h
src/vision/cameras/SIMCam.cpp
src/vision/cameras/SIMCam.h
src/vision/cameras/ZEDCam.cpp
src/vision/cameras/ZEDCam.h

Key Features:
- Easy toggling of camera recording for each camera and tag detector feed with constants.
- Code is written to enumerate any cameras added. (Recording handler shouldn't need to be modified when cameras are added to CameraHandler or TagDetectionHandler)
- Recording FPS will be adjustable to allow for savings on CPU time and disk space.
- Recordings are saved to timestamped folders and organized based on time program is started, handler, and camera name or path.
Other Changes:
- All .log console output files are now saved to the same timestamped folder as the videos. Basically each program start creates a new timestamped folder that all videos and .log files are saved to for that run.
- The output log path is easily adjustable through a file path string in AutonomyConstants
- …

Implement Camera Recording Handler

---

.devcontainer/Dockerfile_Focal
.devcontainer/Dockerfile_Jammy
.devcontainer/Dockerfile_JetPack
.devcontainer/devcontainer.json
.github/workflows/deploy_docker.yml

Upgrades Quill to v3.6.0
Moves arguments to be with install step to prevent rebuilding whole image over one package getting updated.

Reconfigure the docker files and builder some

---

src/algorithms/DifferentialDrive.hpp
src/algorithms/controllers/PIDController.cpp
src/algorithms/controllers/PIDController.h
src/drivers/DriveBoard.cpp
src/drivers/DriveBoard.h

Added controllers namespace to PIDController class in preparation for other controllers (like StanleyController) being implemented.
StanleyController in topic/#170 already has this namespace.

Added controllers namespace to PIDController.

---

src/algorithms/SearchPattern.hpp
src/util/GeospatialOperations.hpp
tests/Unit/src/algorithms/SearchPattern.cc

Implement unit test to verify general outward spiral pattern.
Resolves #191

 Write Search Pattern Unit Tests #191 

---

tests/Unit/src/algorithms/controllers/StanleyController.cc

When the UTM coordinates in the test case were converted to GPS coordinates, their northing and easting were out of the [1200km, 2800km] range. 
This PR will shift the UTM coordinates by 2000km in both the north and east directions. 
I did this with a constant `UTM_SHIFT` so that the coordinates positions relative to each other is still intuitive and easy to visualize.

Fixed StanleyController Unit Test UTM to GPS conversions.

---

CMakeLists.txt
src/drivers/NavigationBoard.cpp
src/main.cpp

- Update RoveComm commit to fix hanging issues on program exit
- Add subscribe command to NavBoard.

Update RoveComm and Subscribe to NavBoard

---

.github/workflows/valgrind.yml
README.md
tools/valgrind/run_valgrind.sh

Due to a static leak in one of the implementations we are not longer looking to fail that action if a **possibly lost** detection is made.

Reimplement Valgrind

---

.github/workflows/codeql.yml
.github/workflows/deploy_autonomy.yml
.github/workflows/deploy_docker.yml
.github/workflows/tests.yml
.github/workflows/valgrind.yml

To help prevent conflicts between different runner steps we now manually setup and cleanup the environment into the action process.

Add Setup and Clean Action Runners Steps

---

.github/workflows/deploy_autonomy.yml
.github/workflows/tests.yml
.github/workflows/valgrind.yml
CMakeLists.txt

- Fix CMAKE configure errors.
- Fix occasional git repo trust issue while checking out in actions.

Fix Occasional Actions CMAKE Failure

---

.github/workflows/tests.yml
tools/action-runners/Dockerfile_Jammy
tools/action-runners/Dockerfile_JetPack

Since our end hardware application is ARM64 it makes since to do testing at that level as well in GitHub Actions.

Add Unit Testing to ARM64

---

.github/workflows/codeql.yml
.github/workflows/deploy_autonomy.yml

This pull request resolves two key issues in the Autonomy Software project: the `Deploy Autonomy` GitHub Action and CodeQL timeouts. The fix ensures that the deployment process properly uploads the release installer, allowing for seamless uploads during the release phase. Additionally, CodeQL timeouts have been addressed, improving the overall efficiency and reliability of the deployment pipeline.
Changes include:
This update improves the reliability and functionality of the deployment pipeline.

[HOTFIX] Deploying Autonomy and CodeQL Timeouts

---

src/drivers/MultimediaBoard.cpp
src/drivers/NavigationBoard.cpp
src/handlers/StateMachineHandler.cpp
src/handlers/StateMachineHandler.h
src/states/ApproachingMarkerState.cpp
src/states/IdleState.cpp
src/states/NavigatingState.cpp
src/states/VerifyingMarkerState.cpp
src/states/VerifyingObjectState.cpp
src/states/VerifyingPositionState.cpp

Small code cleanup and logic changes. Also fix compile warning.

Cleanup and fix compile warning.

---

src/AutonomyLogging.cpp

Resolve CodeQL Detected Security Alert
Resolves #276

Fix Time Function in Logging

---

.github/workflows/coverage.yml
CMakeLists.txt
data/Custom_Dictionaries/Autonomy-Dictionary.txt

This pull request introduces a new GitHub Action for checking code coverage in the Autonomy Software repository. It ensures that code coverage metrics are automatically generated and included in the CI pipeline. Key changes include:
- Added a code coverage tool integration to the CI workflow.
- Added `.github/workflows/coverage.yml` to include code coverage checking as part of the continuous integration process.
- Set up a reporting step that provides visibility into code coverage metrics after each CI run.
This PR implements code coverage checking.
This PR does not introduce any feature changes to the application code itself, only enhancements to the CI process. It will help improve software quality by providing insights into test coverage.

Add Code Coverage Checking to CI Pipeline

---

.github/workflows/tests.yml

Apparently something didn't merge correctly earlier with https://github.com/MissouriMRDT/Autonomy_Software/pull/321. This should fix it.

[CRITICAL FIX] All Unit/Integration Tests Skipped (cont.)

---

CMakeLists.txt
src/AutonomyConstants.h
src/drivers/NavigationBoard.cpp
src/handlers/StateMachineHandler.cpp
src/handlers/WaypointHandler.cpp
src/states/IdleState.cpp
src/states/NavigatingState.cpp
src/states/ReversingState.cpp
src/states/SearchPatternState.cpp
src/states/StuckState.cpp
src/vision/cameras/ZEDCam.cpp

This PR implements the new log level introduced in the latest version of Quill
- Changed some of the LOG_WARNINGS that were meant to bring attention to a log, but not necessarily dangerous to LOG_NOTICE.

Implement LOG_NOTICE from New Quill Version

---

.devcontainer/Dockerfile_Jammy
.devcontainer/Dockerfile_JetPack

Adds some quality of life packages to the docker environments

Add Useful Packages

---

tools/package-builders/abseil/abseil-amd64-pkg.sh
tools/package-builders/abseil/abseil-arm64-pkg.sh
tools/package-builders/ffmpeg/ffmpeg-amd64-pkg.sh
tools/package-builders/ffmpeg/ffmpeg-arm64-pkg.sh
tools/package-builders/geolib/geolib-amd64-pkg.sh
tools/package-builders/geolib/geolib-arm64-pkg.sh
tools/package-builders/gtest/gtest-amd64-pkg.sh
tools/package-builders/gtest/gtest-arm64-pkg.sh
tools/package-builders/libdatachannel/libdatachannel-amd64-pkg.sh
tools/package-builders/libdatachannel/libdatachannel-arm64-pkg.sh
tools/package-builders/opencv/opencv-amd64-pkg.sh
tools/package-builders/opencv/opencv-arm64-pkg.sh
tools/package-builders/pytorch/pytorch-amd64-pkg.sh
tools/package-builders/pytorch/pytorch-arm64-pkg.sh
tools/package-builders/quill/quill-amd64-pkg.sh
tools/package-builders/quill/quill-arm64-pkg.sh
tools/package-builders/tensorflow/tensorflow-amd64-pkg.sh
tools/package-builders/tensorflow/tensorflow-arm64-pkg.sh

Implement cleaner method of creating the dpkg control files
resolves #352

Implement cleaner method of creating the dpkg control files
