MissouriMRDT/Autonomy_Software

.github/workflows/docker_jetpack.yml, .github/workflows/docker_ubuntu.yml
Make it so that the docker builder has to be run via a manual start from the GitHub Actions Panel. This is to prevent the error that occurs when the number of commits goes into the next "set of 100".
Due to the few number of times this will need to be run, it makes since to have it run manually.
=> Disable Automatic Running of Docker Builders

.gitmodules, CMakeLists.txt
Revamped [RoveComm_CPP](https://github.com/MissouriMRDT/RoveComm_CPP) to be built as a CMake Static Library that is imported into the project when CMake is configured. See [RoveComm_CPP PR#1](https://github.com/MissouriMRDT/RoveComm_CPP/pull/1) for changes that were made on the RoveComm side.
closes #32
=> Switch RoveComm_CPP from submodule to CMake Static Library

.github/workflows/doxygen_generate.yml
Only allow documentation to be re-generated when a pull request is merged successfully into the development branch. Or, the action is manually triggered on the development branch.
=> [HOTFIX] Limit when documentation is updated.

.gitignore, README.md
Added a "fancy" header block to the master project README file. This makes the README look nicer on GitHub and doesn't cause any issues with the Doxygen Project Documentation Site.
=> Add header block to project README

src/states/README.md
Doxygen is run from the root directory so image/file paths have to be made based on the root directory while markdown is based on the relative scope. Only one of the two images is shown at a time.
=> Add "duplicate" image reference

.devcontainer/Dockerfile_JetPack5, .devcontainer/Dockerfile_Ubuntu20, .devcontainer/Dockerfile_Ubuntu22, .devcontainer/devcontainer.json, README.md
Whenever there is new release of JetPack or Ubuntu, it takes a long time for new versions of the `stereolabs/zed` docker images to be released.
We have now switched to using the base docker image from the `stereolabs/zed` docker images and are manually installing the ZED SDK as well as all the packages we were already installing. This should allow for us to have more up-to-date images.
_Note: The new images have been built and work as expected. I have pushed them and will assign the latest tag after this pull request is approved and merged._
=> Docker Image Updates

.devcontainer/devcontainer.json, src/drivers/DriveBoard.cpp, src/drivers/DriveBoard.h, src/drivers/MultimediaBoard.cpp, src/drivers/MultimediaBoard.h
By removing unused parameters from functions we will not be hitting any warnings on build.
Note: This doesn't fix the warnings in the state machine. This will be fixed in a future Pull Request.
=> Fix Project Warnings

src/main.cpp
This PR fixes a bug in main.cpp that would always execute the RunExample() function even if an example wasn't included.
Closes issue #105
=> [BUG] Examples Runner

src/states/AbortState.hpp, src/states/ApproachingGateState.hpp, src/states/ApproachingMarkerState.hpp, src/states/AvoidanceState.hpp, src/states/IdleState.hpp, src/states/NavigationState.hpp, src/states/ReverseState.hpp, src/states/SearchPatternState.hpp, src/states/StuckState.hpp
- Added a `(void)` call in front of unused state machine parameters that will eventually get removed with new implementation of the state machine.
=> Remove all warnings from application

CMakeLists.txt
- RoveComm Library was looking for a non existant header file from an older implementation of the library. missourimrdt/rovecomm_cpp@85ef67dab352652cb38a9ff8650e3aa5de31e7d0
- RoveComm Library was looking in wrong location for install instructions file. missourimrdt/rovecomm_cpp@608453f6b3e1a4445d281020d7dea568f7bf5e8d
Closes #112
=> Fix `make install` breaks during link to RoveComm

.devcontainer/devcontainer.json
The CMAKE extension recently had an update that defaults to hiding the toolkit and config settings. Reset the visibility of those options to show up in the bottom toolbar.
=> Fix CMAKE Extension Settings Not Showing In Bottom Toolbar

examples/vision/tagdetection/ArucoDetectionBasicCam.hpp, src/AutonomyConstants.h, src/handlers/RecordingHandler.cpp, src/handlers/TagDetectionHandler.cpp, src/interfaces/AutonomyThread.hpp, src/interfaces/Camera.hpp, src/main.cpp, src/vision/aruco/TagDetector.cpp, src/vision/aruco/TagDetector.h, src/vision/cameras/ZEDCam.cpp
- Improvements to logging file structure and output.
- Changed VideoWriter output from .MP4 to .MKV. This should reduce filesize and help with preventing loss of video logging during a crash or shutdown.
- The TagDetectionHandler::StopAllDetectors() method now also shuts down the RecordingHandler for the tag detectors. (Just like the CameraHandler::StopAllCameras() method)
- Fixed an issue with the TagDetector class causing the program to segfault if the cameras were previously started, but are now shutdown.
- Reorganized AutonomyThread.hpp and added more comprehensive thread state tracking instead of just a simple running/not running boolean.
- Added Ctrl+C interruption handling for graceful shutdowns and cleanup actions.
- main.cpp now has an official while loop to keep the program …
=> HOTFIX: Camera Recorder and General Bug Fixes

INSTALL.md, src/main.cpp, src/vision/aruco/TagDetector.cpp, src/vision/aruco/TagDetector.h, src/vision/cameras/BasicCam.cpp, src/vision/cameras/ZEDCam.cpp
Main Changes:
- Because the IPS instance was moved to AutonomyThread, whereas it was originally placed in Camera.hpp, the Tick() method was getting called twice. Once from inside AutonomyThread and sometimes once from inside the child class's ThreadedContinuousCode(). This lead to very high FPS numbers.
Other Changes:
- Updated the docker install link to point to Docker Engine instead of Docker Desktop. Docker Desktop seems to have too many issues on anything other than Windows.
=> AutonomyThread IPS Inaccurate

README.md
Since we have started using the **latest** tag for our docker images, to make there be less things that have to update when we push a new image, I am just now getting around to getting the README to not need to be updated anymore.
=> Update Docker Images on README

src/AutonomyConstants.h, src/algorithms/DifferentialDrive.hpp, src/drivers/DriveBoard.cpp
- Added missing parameter description to docs
- Moved logging statements to be more clean.
- Adjusted constants to be more consistent.
=> DriveBoard Class and `diffdrive` Namespace Cleanup

src/handlers/StateMachineHandler.h
Moved the inherited methods from AutonomyThread from Public to Private Scope
Resolves #176
=> Fix State Machine Inheritance Scope

.github/workflows/tests.yml
GitHub has deprecated a method used by v2 of the file existence action plugin. It has been resolved in v3.
The file existence plugin aids us in figuring out if we have unit tests existing in a directory.
=> [HOTFIX] - File Existence Plugin

.github/workflows/doxygen_generate.yml
GitHub has deprecated support for some code used by older versions of the GitHub Pages packages we are using and Doxygen was also on an older version of the syntax.
We use GitHub Pages for hosting our API docs which are generated using Doxygen.
=> [HOTFIX] - GitHub Pages and Doxygen Actions

.github/workflows/deploy_autonomy.yml
GitHub has deprecated a method used by v2 of the artifact action plugins. It has been resolved in v4.
We use these to add and remove files from the artifacts published with GitHub Actions.
=> [HOTFIX] - GitHub Artifacts Plugin

src/algorithms/planners/AStar.cpp
Just changed `#include "../../AutonomyGlobals.h` to `#include "../../AutonomyLogging.h"` to cleanup dependency graphs.
This was missed during the ASTAR PR reviews, didn't notice it until looking at dependency graphs for AStar.cpp in doxygen.
=> [HOTFIX] Missed inappropriate #include from AStar merge.

.github/workflows/deploy_docker.yml
Fix the build architecture for JetPack images.
Some how our JetPack images have been build for the AMD64 Architecture since late December.
=> [HOTFIX] Fix JetPack Build Architecture

src/drivers/NavigationBoard.cpp, src/drivers/NavigationBoard.h, src/handlers/StateMachineHandler.h, src/main.cpp
- Added velocity calculation to navboard rovecomm callback.
- **This will be useful for the stuck state and perhaps searchpattern**
- Added accessor for getting rover velocity and latest GPS data timestamp.
- Changed StateMachineHandler's AutonomyThread parent class to be private since users are meant to call StateMachineHandler methods for starting and stopping the state machine (not directly use AutonomyThread methods)
- `GetIPS()` is still accessible for getting FPS info of the background thread.
- Changed thread FPS to be a debug print and added it to the file logger.
=> Add GPS Based Rover Velocity Calculation to NavBoard

.devcontainer/Dockerfile_Jammy, .devcontainer/Dockerfile_JetPack, tools/package-builders/quill/quill-amd64-pkg.sh, tools/package-builders/quill/quill-arm64-pkg.sh
- Fixed crash triggered by insufficient space in the queue upon invocation of flush(). 
- Fixed windows clang-cl build error.
- Fixed compilation errors encountered on FreeBSD and extended get_thread_id() support to various other BSD operating systems.
- Fix open_file() in the FileHandler to also create the parent path before opening the file.
- Enhance logic for backend thread's flush() invocation; it now triggers only if the handler has previously written data.
- Address an uncaught exception in the backend thread that could occur when a user manually removes the log file from the terminal while the logger is running.
- Ensure that after a logger is removed, there are no subsequent calls to the Handler's flush() or run_loop(), provided the Handler is not shared.
- Ignore the virtual …
=> Upgrade to Quill 3.7.0

tests/Unit/src/util/IPS.cc
Floating point error was causing the unit test to occasionally fail.
=> Fix IPS Unit Test

src/vision/cameras/ZEDCam.cpp
Remove double mutex unlock to fix ZEDCam threads not running.
=> Fix ZEDCam freeze.

.devcontainer/devcontainer.json, CONTRIBUTING.md
Updates the settings and highlights for the TODO Tree extension. It adds exclusion globs for CONTRIBUTING.md file, and modifies the tags and custom highlights to include different variations of TODO, BUG, HACK, FIXME, LEAD, ISSUE NOTE, and TEST.
=> Update TODO Tree extension settings and highlights

src/AutonomyConstants.h, src/main.cpp
- Readd ZED depth model to fix bind errors with container.
- Enable spatial mapping for fun. Will be interesting to see how it does during testing.
=> Fix Missing Bind Directory on Container Start

data/Custom_Dictionaries/Autonomy-Dictionary.txt, examples/vision/cameras/OpenBasicCam.hpp, examples/vision/dnn/InferenceYOLOModel.hpp, examples/vision/tagdetection/ArucoDetectionBasicCam.hpp, src/AutonomyConstants.h, src/handlers/CameraHandler.cpp, src/handlers/CameraHandler.h, src/handlers/ObjectDetectionHandler.cpp, src/handlers/ObjectDetectionHandler.h, src/handlers/StateMachineHandler.cpp, src/handlers/StateMachineHandler.h, src/handlers/TagDetectionHandler.cpp, src/handlers/TagDetectionHandler.h, src/main.cpp, src/states/ApproachingMarkerState.cpp, src/states/IdleState.cpp, src/states/SearchPatternState.cpp, src/vision/aruco/TagDetector.cpp
- Change Handlers to reflect this year's camera layout.
- Autonomy will now forcefully enter IdleState if battery cell voltage gets below an average 3.2 volts per cell.
=> Reconfigure Camera Layout and Add Battery Voltage Monitoring

.devcontainer/devcontainer.json, README.md
- Update main README.md to reflect new image and C++ versions.
- Set VSCode git extension to not show submodules. (just cleanup and less confusing for members when committing and creating new branches)
=> Update README and Git Extension Settings.

.devcontainer/devcontainer.json, data/Custom_Dictionaries/Autonomy-Dictionary.txt, src/AutonomyLogging.cpp
Docker by default uses universal standard time however that causes the loggers and documentation to have incorrect timestamps associated with them. This fixes that and allows for easier debugging and log tracking.
**devcontainer.json**:
- Binded the host systems time and date file to the development container.
**AutonomyLogging.cpp**:
- Switched from GMT to LocalTime since it works and will be easier for bug tracking.
**Autonomy-Dictionary.txt**:
- Added "LocalTime" to custom dictionary.
=> Fix Local Time in Containers

.github/workflows/codeql.yml, .github/workflows/deploy_autonomy.yml, .github/workflows/deploy_docker.yml
This PR implements restrictions on who can trigger the `Deploy Autonomy` and `Rebuild Docker` GitHub Action Jobs within the Autonomy Software project. Due to the significant computing power required to run these actions, it is essential to limit access to only those with the appropriate permissions.
**Key Changes:**
- Permission Enforcement: Added role-based restrictions to the `Deploy Autonomy` and `Rebuild Docker` GitHub Action Jobs, ensuring that only authorized users, such as Admins or Maintainers, can initiate these resource-intensive workflows.
- Workflow Updates: Modified the YAML configurations for the affected actions to check for required permissions before execution.
**Benefits:**
- Resource Management: Helps prevent unnecessary or unauthorized consumption of computing …
=> Restrict Permissions for High-Resource GitHub Actions: Deploy Autonomy & Rebuild Docker

CMakeLists.txt, src/drivers/MultimediaBoard.cpp, src/states/ApproachingMarkerState.cpp, src/states/ApproachingMarkerState.h, src/states/ApproachingObjectState.cpp, src/states/NavigatingState.cpp, src/states/NavigatingState.h, src/states/SearchPatternState.cpp, src/states/VerifyingMarkerState.cpp, src/states/VerifyingObjectState.cpp, src/vision/aruco/TagDetector.cpp, src/vision/aruco/TagDetector.h
- Change the TagDetector class to use the regular RGB image from the ZEDCam instead of the split PointCloud colors. This prevents the tag itself from being masked out at long distances due to bad depth information.
- Add tag detection to NavigatingState
- Fix the NavigatingState so that it doesn't pop waypoints. Only the verify state can.
- Fix approaching marker so that it goes back to the calling state instead of the SearchPatterState if the marker is unseen.
NOTE: ApproachingMarkerState currently doesn't use the VerifyingMarkerState. When this is eventually used, remove all PopNextWaypoint calls from the state.
- Fix segfault from MultimediaBoard
=> Tag Detection Tweaks and State Machine Bug Fixes

.github/workflows/tests.yml, CMakeLists.txt
This PR addresses two issues in the Autonomy Software repository:
1. Fixes an issue in the `tests.yml` where a variable was not being passed correctly.
2. Re-applies the `CMAKE Project Version`, which was mistakenly deleted in a previous commit.
- **Fixed `tests.yml`:** Corrected the variable passing to ensure that all necessary parameters are correctly passed during the test runs.
- **Restored `CMAKE Project Version`:** The `CMAKE Project Version` was accidentally removed in a previous commit. This hotfix reinstates it to maintain proper versioning in the CMake configuration.
- The incorrect variable passing in the `tests.yml` was causing issues in the test pipeline, leading to tests running for longer than expected during CI/CD.
- The missing `CMAKE Project Version` caused build …
=> Hotfix: Fix tests.yml Variable Passing and Restore CMAKE Project Version

.github/workflows/tests.yml
When logic was added to make sure that we weren't wasting compute time in the unit testing runners by skipping tests building tests if they don't exist in 57ad59f. The directory path to the tests directory was miss typed and not caught until now.
ClickUp: CU-8689nmmur
=> [CRITICAL FIX] All Unit/Integration Tests Skipped

src/handlers/TagDetectionHandler.h, src/vision/aruco/ArucoDetection.hpp, src/vision/aruco/TagDetector.cpp, src/vision/aruco/TensorflowTagDetection.hpp
Add some sanity checks to TagDetector and temporarily comment out cv::Filter2D.
- Add checks for proper image formats and dimensions.
- Comment out cv::Filter2D, which was causing TagDetector blowout.
- Update RoveComm_CPP submodule commit.
=> TagDetector Cleanup and Update RoveComm_CPP Submodule

README.md
Remove Valgrind Action from README now that we have removed the workflow
=> Update README.md and RoveComm to v25.2.2

.devcontainer/Jammy.dockerfile, .devcontainer/JetPack.dockerfile, .devcontainer/devcontainer.json, .github/workflows/tests.yml
A removal of gfortran from the dockerfile as it is not used anywhere in the codebase and is thus not needed. 
Removed `gfortran` from the jammy and jetPack dockerfiles APT installed packages. 
Adam will hate this and say this PR is blasphemy.
=> Removed gfortran as it was not being used

src/AutonomyConstants.cpp, src/AutonomyConstants.h, src/drivers/DriveBoard.cpp, src/main.cpp, src/states/ApproachingMarkerState.cpp, src/states/ApproachingObjectState.cpp, src/states/NavigatingState.cpp, src/states/SearchPatternState.cpp, src/states/VerifyingObjectState.cpp, src/vision/aruco/TagDetector.cpp, src/vision/aruco/TagDetector.h, src/vision/objects/ObjectDetector.cpp, src/vision/objects/ObjectDetector.h
Weekend test‐driven tweaks to rover autonomy: updated drive limits, cleaned up RoveComm telemetry, tightened clamp logic, and streamlined detection code.
* **RoveComm**: Bumped manifest IDs/counts in submodule.
* **Drive Limits**: `DRIVE_MAX_EFFORT` ↑ 0.4 → 0.5 (and min → –0.5); motor powers now scale off this.
* **Clamp Logic**: Removed `MapRange`; direct clamp to effort range in `DriveBoard`.
* **Telemetry Types**: Switched FPS vector/index in `main.cpp` from `int` → `uint32_t`.
* **Stuck Detection**: Wrapped checks behind `*_ENABLE_STUCK_DETECT` flags in all states.
* **Visualization**: Changed object‐dot color to purple; eliminated redundant color‐space conversions in detection.
Constants drive all power settings; clamping uses unified effort bounds; stuck checks only run when …
=> Testing Mallet Detection (bug fixes and cleanup)
